name: sonicity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  clipboard: ^0.1.3
  cloud_firestore: ^4.14.0
  feedback: ^3.0.1
  file_manager: ^1.0.2
  file_picker: ^6.1.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_expandable_fab: ^2.0.0
  flutter_glow: ^0.3.0
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  http: ^1.2.0
  iconify_flutter_plus: ^1.0.3
  intl: ^0.18.1
  line_awesome_flutter: ^2.0.0
  lottie: ^3.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.1
  rename: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  super_string: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/appLogo150x150.png"

flutter:
  uses-material-design: true
  fonts:
    - family: LovelyMamma
      fonts:
        - asset: assets/fonts/lovelyMamma.ttf
  assets:
    - lib/.env
    - assets/images/
    - assets/lottie/
