name: sonicity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rename: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/appLogo.jpg"

flutter:
  uses-material-design: true
  fonts:
    - family: LovelyMamma
      fonts:
        - asset: assets/fonts/lovelyMamma.ttf
