name: glowy_borders
description: A package for making your borders glow up
version: 1.0.2
homepage: https://inferialize.com
repository: https://github.com/saschTa/flutter_glowy_borders


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1