export 'cloned_database.dart';
export 'home_database.dart';
export 'my_playlists_database.dart';
export 'recents_database.dart';
export 'starred_database.dart';


const tbSongDetail = 'cloned_song';
const tbAlbumDetail = 'cloned_album';
const tbArtistDetail = 'cloned_artist';
const tbPlaylistDetail = 'cloned_playlist';
const tbTrendingSongs = 'trending_songs';
const tbTrendingAlbums = 'trending_albums';
const tbTopCharts = 'top_charts';
const tbTopAlbums = 'top_albums';
const tbHotPlaylists = 'hot_playlist';
const tbPlaylistDetails = 'playlist_details';
const defaultImg = 'assets/images/myPlaylistCover/myPlaylistCover50x50.jpg${specCharQuality}assets/images/myPlaylistCover/myPlaylistCover150x150.jpg${specCharQuality}assets/images/myPlaylistCover/myPlaylistCover500x500.jpg';
const specCharSong = '(*_*)';
const specCharQuality = '[*]';

const colId = 'id';
const colSongId = 'song_id';
const colAlbumId = 'album_id';
const colArtistId = 'artist_id';
const colPlaylistId = 'playlist_id';
const colName = 'name';
const colAlbumName = 'album_name';
const colArtistIds = 'artist_ids';
const colArtistNames = 'artist_names';
const colHasLyrics = 'hasLyrics';
const colYear = 'year';
const colReleaseDate = 'releaseDate';
const colDuration = 'duration';
const colLanguage = 'language';
const colSongCount = 'songCount';
const colDominantType = 'dominantType';
const colImgLow = 'img_low';
const colImgMed = 'img_med';
const colImgHigh = 'img_high';
const colDownload12kbps = 'download_12kbps';
const colDownload48kbps = 'download_48kbps';
const colDownload96kbps = 'download_96kbps';
const colDownload160kbps = 'download_160kbps';
const colDownload320kbps = 'download_320kbps';
const colDateCreated = 'date_created';
const colImages = 'images';
const colSongIds = 'song_ids';